# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # vagrant plugin install vagrant-vbguest
  # vagrant up
  # both machines have default credentials vagrant/vagrant
  # tested with virtualbox provider
  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "private_network", ip: "192.168.33.10"
    web.vm.hostname = "pycon8-web"
    web.ssh.forward_agent = true
    web.ssh.insert_key = false
    web.vm.boot_timeout = 120
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.network "forwarded_port", guest: 5432, host: 54321
    db.vm.network "private_network", ip: "192.168.33.11"
    db.vm.hostname = "pycon8-db"
    db.ssh.forward_agent = true
    db.ssh.insert_key = false
    db.vm.boot_timeout = 120
  end
end
