---

- hosts: web-servers
  roles:
    - role: python_app
      app_name: pycon8
      http_port: 80
      version: "{{ pycon8 }}"
      git_repo: "https://github.com/marco-santamaria/django-ansible-deploy.git"
      when: pycon8 is defined
